// packages/app/src/plugin/PluginHost.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { ReactElement } from 'react';
  import { render, createRenderer, type ExtendedRenderBridge } from '@svelte-react-render/api';
  import type { SvelteComponentInstance } from '@svelte-react-render/api';
  import ComponentRenderer from './ComponentRenderer.svelte';

  interface Props {
    plugin: ReactElement;
  }

  let { plugin }: Props = $props();

  let bridge: ExtendedRenderBridge | null = $state(null);
  let rootInstance = $state<SvelteComponentInstance | null>(null);
  let unsubscribe: (() => void) | null = null;

  onMount(() => {
    // Create a render bridge
    const newBridge = createRenderer();
    bridge = newBridge;

    // Subscribe to bridge updates
    unsubscribe = newBridge.subscribe(() => {
      console.log('PluginHost: Bridge update triggered', {
        rootInstance: newBridge.rootInstance,
        rootInstanceId: newBridge.rootInstance?.id,
        rootInstanceType: newBridge.rootInstance?.type
      });
      // Direct assignment triggers Svelte reactivity
      rootInstance = newBridge.rootInstance;
      console.log('PluginHost: rootInstance updated');
    });

    // Render the plugin immediately after setting up the subscription
    console.log('PluginHost: Rendering plugin');
    render(plugin, newBridge);
  });

  onDestroy(() => {
    if (unsubscribe) {
      unsubscribe();
    }
  });
</script>

<div class="w-full h-full">
  {#if rootInstance}
    <ComponentRenderer instance={rootInstance} />
  {:else}
    <div class="w-full h-full flex items-center justify-center text-gray-500 text-sm">
      Loading plugin…
    </div>
  {/if}
</div>

// packages/demo-react/src/lib/plugin/PluginHost.tsx
import { useEffect, useState, useRef, type ReactElement } from 'react';
import { render, createRenderer, type ExtendedRenderBridge } from '@svelte-react-render/api';
import type { SvelteComponentInstance } from '@svelte-react-render/api';
import { ComponentRenderer } from './ComponentRenderer';

interface PluginHostProps {
  plugin: ReactElement;
}

export function PluginHost({ plugin }: PluginHostProps) {
  const [rootInstance, setRootInstance] = useState<SvelteComponentInstance | null>(null);
  const bridgeRef = useRef<ExtendedRenderBridge | null>(null);
  const unsubscribeRef = useRef<(() => void) | null>(null);

  useEffect(() => {
    const newBridge = createRenderer();
    bridgeRef.current = newBridge;

    unsubscribeRef.current = newBridge.subscribe(() => {
      console.log('PluginHost: Bridge update triggered');
      setRootInstance(newBridge.rootInstance);
    });

    console.log('PluginHost: Rendering plugin');
    render(plugin, newBridge);

    return () => {
      if (unsubscribeRef.current) {
        unsubscribeRef.current();
      }
    };
  }, []);

  useEffect(() => {
    if (bridgeRef.current) {
      console.log('PluginHost: Plugin changed, re-rendering');
      render(plugin, bridgeRef.current);
    }
  }, [plugin]);

  return (
    <div className="h-full w-full">
      {rootInstance ? (
        <ComponentRenderer instance={rootInstance} />
      ) : (
        <div className="flex h-full w-full items-center justify-center text-sm text-gray-500">
          Loading plugin…
        </div>
      )}
    </div>
  );
}
