// packages/demo-react/src/lib/plugin/components/PluginInput.tsx
import { useState, useEffect } from "react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

interface PluginInputProps {
  id?: string;
  value?: string;
  defaultValue?: string;
  placeholder?: string;
  label?: string;
  type?: string;
  onChange?: (value: string, event?: React.ChangeEvent<HTMLInputElement>) => void;
  onInput?: (value: string, event?: React.ChangeEvent<HTMLInputElement>) => void;
  className?: string;
}

export function PluginInput({
  id,
  value,
  defaultValue,
  placeholder,
  label,
  type = 'text',
  onChange,
  onInput,
  className
}: PluginInputProps) {
  const [internalValue, setInternalValue] = useState(value ?? defaultValue ?? '');

  useEffect(() => {
    if (value !== undefined) {
      setInternalValue(value);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value]);

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = event.target.value;
    setInternalValue(newValue);
    onChange?.(newValue);
    onInput?.(newValue);
  };

  return (
    <div className="grid w-full max-w-sm items-center gap-1.5">
      {label && <Label htmlFor={id}>{label}</Label>}
      <Input
        id={id}
        type={type}
        placeholder={placeholder}
        value={internalValue}
        onChange={handleChange}
        className={className}
      />
    </div>
  );
}

// packages/demo-vue/src/lib/plugin/components/PluginInput.vue
<script setup lang="ts">
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label'; // We need Label component, assume it exists or I'll check
import { ref, watch, onMounted } from 'vue';

interface Props {
  id?: string;
  value?: string;
  defaultValue?: string;
  placeholder?: string;
  label?: string;
  type?: string;
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  type: 'text'
});

const emit = defineEmits<{
  (e: 'change', value: string): void;
  (e: 'input', value: string): void;
}>();

const internalValue = ref(props.value ?? props.defaultValue ?? '');

watch(() => props.value, (newValue) => {
  if (newValue !== undefined) {
    internalValue.value = newValue;
  }
});

const handleChange = (payload: string | number) => {
  const newValue = String(payload);
  internalValue.value = newValue;
  emit('change', newValue);
  emit('input', newValue);
};
</script>

<template>
  <div class="grid w-full max-w-sm items-center gap-1.5">
    <Label v-if="label" :for="id">{{ label }}</Label>
    <Input
      :id="id"
      :type="type"
      :placeholder="placeholder"
      :model-value="internalValue"
      @update:model-value="handleChange"
      :class="props.class"
    />
  </div>
</template>
