// packages/demo-sveltekit/src/lib/plugin/WebSocketPluginHost.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { RPCChannel, WebSocketClientIO } from 'kkrpc';
	import ComponentRenderer from './ComponentRenderer.svelte';
	import type { WorkerAPI, MainThreadAPI, SerializedComponentTree } from './worker-rpc-types';

	interface Props {
		serverUrl: string;
		props?: any;
	}

	let { serverUrl, props: pluginProps = {} }: Props = $props();

	let rootInstance = $state<SerializedComponentTree | null>(null);
	let rpc: RPCChannel<MainThreadAPI, WorkerAPI> | null = null;
	let ws: WebSocket | null = null;
	let isLoading = $state(true);
	let error = $state<string | null>(null);
	let reconnectAttempts = $state(0);
	let maxReconnectAttempts = 5;
	let reconnectDelay = 1000;

	// Store RPC in a way that ComponentRenderer can access it
	let rpcContext = $state<{ rpc: RPCChannel<MainThreadAPI, WorkerAPI> | null }>({ rpc: null });

	let lastServerUrl = $state<string | null>(null);

	async function connectToServer(url: string) {
		try {
			console.log('[Client] Connecting to plugin server:', url);
			isLoading = true;
			error = null;

			// Close existing connection if any
			if (ws) {
				console.log('[Client] Closing existing WebSocket connection');
				ws.close();
				ws = null;
				rpc = null;
			}

			// Create WebSocket connection
			ws = new WebSocket(url);
			console.log('[Client] WebSocket connection initiated');

			// Wait for connection to open
			await new Promise<void>((resolve, reject) => {
				const timeout = setTimeout(() => {
					reject(new Error('WebSocket connection timeout'));
				}, 10000);

				ws!.onopen = () => {
					clearTimeout(timeout);
					console.log('[Client] WebSocket connection established');
					resolve();
				};

				ws!.onerror = (err) => {
					clearTimeout(timeout);
					reject(new Error(`WebSocket connection failed: ${err}`));
				};
			});

			// Initialize RPC channel
			const io = new WebSocketClientIO(ws);

			rpc = new RPCChannel<MainThreadAPI, WorkerAPI>(io, {
				expose: {
					updateComponentTree(tree: SerializedComponentTree | null) {
						console.log('[Client] Received component tree update');
						rootInstance = tree;
						isLoading = false;
						reconnectAttempts = 0; // Reset reconnect attempts on successful connection
					},
					logMessage(level: 'log' | 'warn' | 'error' | 'info', ...args: any[]) {
						console[level]('[Plugin]', ...args);
					}
				}
			});

			rpcContext.rpc = rpc;
			lastServerUrl = url;

			console.log('[Client] RPC channel initialized');

			// Call the server's initialize method to start the plugin
			try {
				const api = rpc.getAPI();
				await api.initialize(pluginProps);
				console.log('[Client] Plugin initialized successfully');
			} catch (initError) {
				console.error('[Client] Failed to initialize plugin:', initError);
				error = initError instanceof Error ? initError.message : String(initError);
				isLoading = false;
			}
		} catch (err) {
			console.error('[Client] Error connecting to plugin server:', err);
			error = err instanceof Error ? err.message : String(err);
			isLoading = false;

			// Attempt reconnection if not at max attempts
			if (reconnectAttempts < maxReconnectAttempts) {
				reconnectAttempts++;
				console.log(`[Client] Reconnection attempt ${reconnectAttempts}/${maxReconnectAttempts} in ${reconnectDelay}ms`);

				setTimeout(() => {
					connectToServer(url);
				}, reconnectDelay);

				// Exponential backoff
				reconnectDelay = Math.min(reconnectDelay * 2, 30000);
			} else {
				console.error('[Client] Max reconnection attempts reached');
			}
		}
	}

	onMount(() => {
		connectToServer(serverUrl);
	});

	// Watch for server URL changes and reconnect
	$effect(() => {
		// Only trigger if URL actually changed
		if (serverUrl !== lastServerUrl && lastServerUrl !== null) {
			console.log('[Client] Server URL changed, reconnecting:', serverUrl);
			rootInstance = null;
			reconnectAttempts = 0; // Reset for new URL
			reconnectDelay = 1000; // Reset delay
			connectToServer(serverUrl);
		}
	});

	// Watch for prop changes and update
	$effect(() => {
		if (rpc && pluginProps && !isLoading) {
			console.log('[Client] Props changed, updating server');
			const api = rpc.getAPI();
			api.updateProps(pluginProps);
		}
	});

	onDestroy(() => {
		console.log('[Client] Destroying WebSocket plugin host');

		if (rpc) {
			try {
				const api = rpc.getAPI();
				api.destroy();
			} catch (err) {
				console.warn('[Client] Error destroying RPC:', err);
			}
		}

		if (ws) {
			ws.close();
		}
	});

	// Handle WebSocket events
	$effect(() => {
		if (ws) {
			ws.onclose = (event) => {
				console.log('[Client] WebSocket connection closed:', event.code, event.reason);
				if (event.code !== 1000) { // Not a normal closure
					error = `Connection closed: ${event.reason || 'Unknown error'}`;
					isLoading = true;

					// Attempt reconnection for non-normal closures
					if (reconnectAttempts < maxReconnectAttempts) {
						reconnectAttempts++;
						console.log(`[Client] Reconnection attempt ${reconnectAttempts}/${maxReconnectAttempts} in ${reconnectDelay}ms`);

						setTimeout(() => {
							connectToServer(serverUrl);
						}, reconnectDelay);

						reconnectDelay = Math.min(reconnectDelay * 2, 30000);
					}
				}
			};

			ws.onerror = (event) => {
				console.error('[Client] WebSocket error:', event);
			};
		}
	});
</script>

<div class="h-full w-full">
	{#if error}
		<div class="flex h-full w-full items-center justify-center">
			<div class="text-sm text-red-500">
				<div class="mb-2 font-semibold">Connection Error</div>
				<div class="text-xs text-red-400">{error}</div>
				{#if reconnectAttempts > 0 && reconnectAttempts < maxReconnectAttempts}
					<div class="text-xs text-yellow-500 mt-2">
						Reconnecting... ({reconnectAttempts}/{maxReconnectAttempts})
					</div>
				{/if}
				{#if reconnectAttempts >= maxReconnectAttempts}
					<button
						class="mt-2 px-3 py-1 text-xs bg-red-500 text-white rounded hover:bg-red-600"
						onclick={() => {
							reconnectAttempts = 0;
							reconnectDelay = 1000;
							connectToServer(serverUrl);
						}}
					>
						Retry Connection
					</button>
				{/if}
			</div>
		</div>
	{:else if isLoading}
		<div class="flex h-full w-full items-center justify-center text-sm text-gray-500">
			{#if reconnectAttempts > 0}
				Connecting to server... ({reconnectAttempts}/{maxReconnectAttempts})
			{:else}
				Connecting to plugin server…
			{/if}
		</div>
	{:else if rootInstance}
		<ComponentRenderer instance={rootInstance} {rpcContext} />
	{:else}
		<div class="flex h-full w-full items-center justify-center text-sm text-gray-500">
			Waiting for plugin content...
		</div>
	{/if}
</div>

// packages/demo-vue/src/lib/plugin/WebSocketPluginHost.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { RPCChannel, WebSocketClientIO } from 'kkrpc';
import type { WorkerAPI, MainThreadAPI, SerializedComponentTree } from './worker-rpc-types';
import ComponentRenderer from './ComponentRenderer.vue';

interface Props {
  serverUrl: string;
  props?: unknown;
}

const props = withDefaults(defineProps<Props>(), {
  props: () => ({})
});

const rootInstance = ref<SerializedComponentTree | null>(null);
const isLoading = ref(true);
const error = ref<string | null>(null);
const reconnectAttempts = ref(0);
const rpcRef = ref<RPCChannel<MainThreadAPI, WorkerAPI> | null>(null);

const maxReconnectAttempts = 5;
const reconnectDelayRef = ref(1000);
const isInitializedRef = ref(false);
const wsRef = ref<WebSocket | null>(null);
const reconnectTimeoutRef = ref<number | null>(null);
const isConnectingRef = ref(false);

const connectToServer = async (url: string) => {
  if (isConnectingRef.value) return;
  isConnectingRef.value = true;

  try {
    console.log('[Client] Connecting to plugin server:', url);
    isLoading.value = true;
    error.value = null;
    isInitializedRef.value = false;

    if (wsRef.value) {
      wsRef.value.close();
      wsRef.value = null;
      rpcRef.value = null;
    }

    const ws = new WebSocket(url);
    wsRef.value = ws;

    await new Promise<void>((resolve, reject) => {
      const timeout = setTimeout(() => reject(new Error('WebSocket connection timeout')), 10000);

      ws.onopen = () => {
        clearTimeout(timeout);
        console.log('[Client] WebSocket connection established');
        resolve();
      };

      ws.onerror = () => {
        clearTimeout(timeout);
        reject(new Error('WebSocket connection failed'));
      };
    });

    if (wsRef.value !== ws) {
      ws.close();
      return;
    }

    const io = new WebSocketClientIO(ws);
    const rpc = new RPCChannel<MainThreadAPI, WorkerAPI>(io, {
      expose: {
        updateComponentTree(tree: SerializedComponentTree | null) {
          console.log('[Client] Received component tree update');
          rootInstance.value = tree;
          isLoading.value = false;
          reconnectAttempts.value = 0;
          reconnectDelayRef.value = 1000;
        },
        logMessage(level: 'log' | 'warn' | 'error' | 'info', ...args: unknown[]) {
          console[level]('[Plugin]', ...args);
        }
      }
    });

    rpcRef.value = rpc;

    ws.onclose = (event) => {
      console.log('[Client] WebSocket closed:', event.code, event.reason);
      if (event.code !== 1000) {
        error.value = `Connection closed: ${event.reason || 'Unknown error'}`;
        isLoading.value = true;
        scheduleReconnection(url);
      }
    };

    ws.onerror = (event) => console.error('[Client] WebSocket error:', event);

    const api = rpc.getAPI();
    await api.initialize(props.props);
    isInitializedRef.value = true;
    console.log('[Client] Plugin initialized successfully');

  } catch (err) {
    console.error('[Client] Connection error:', err);
    error.value = err instanceof Error ? err.message : String(err);
    isLoading.value = false;
    scheduleReconnection(url);
  } finally {
    isConnectingRef.value = false;
  }
};

const scheduleReconnection = (url: string) => {
  if (reconnectAttempts.value >= maxReconnectAttempts) {
    console.error('[Client] Max reconnection attempts reached');
    return;
  }
  
  reconnectAttempts.value++;
  console.log(`[Client] Reconnection attempt ${reconnectAttempts.value}/${maxReconnectAttempts}`);
  
  reconnectTimeoutRef.value = setTimeout(() => {
    connectToServer(url);
  }, reconnectDelayRef.value);
  
  reconnectDelayRef.value = Math.min(reconnectDelayRef.value * 2, 30000);
};

onMounted(() => {
  connectToServer(props.serverUrl);
});

onUnmounted(() => {
  console.log('[Client] Cleanup WebSocket plugin host');
  
  if (reconnectTimeoutRef.value) {
    clearTimeout(reconnectTimeoutRef.value);
  }
  
  if (wsRef.value) {
    wsRef.value.onclose = null;
    wsRef.value.onerror = null;
    wsRef.value.close();
    wsRef.value = null;
  }
  
  rpcRef.value = null;
  isConnectingRef.value = false;
});

watch(() => props.serverUrl, (newUrl) => {
  reconnectAttempts.value = 0;
  reconnectDelayRef.value = 1000;
  connectToServer(newUrl);
});

watch(() => props.props, (newProps) => {
  if (rpcRef.value && isInitializedRef.value && !isLoading.value) {
    console.log('[Client] Props changed, updating server');
    rpcRef.value.getAPI().updateProps(newProps);
  }
}, { deep: true });

const reload = () => {
  window.location.reload();
};
</script>

<template>
  <div v-if="error" class="flex h-full w-full items-center justify-center">
    <div class="text-sm text-red-500">
      <div class="mb-2 font-semibold">Connection Error</div>
      <div class="text-xs text-red-400">{{ error }}</div>
      <div v-if="reconnectAttempts > 0 && reconnectAttempts < maxReconnectAttempts" class="text-xs text-yellow-500 mt-2">
        Reconnecting... ({reconnectAttempts}/{maxReconnectAttempts})
      </div>
      <button
        v-if="reconnectAttempts >= maxReconnectAttempts"
        class="mt-2 px-3 py-1 text-xs bg-red-500 text-white rounded hover:bg-red-600"
        @click="reload"
      >
        Retry Connection
      </button>
    </div>
  </div>

  <div v-else-if="isLoading" class="flex h-full w-full items-center justify-center text-sm text-gray-500">
    {{ reconnectAttempts > 0 ? `Connecting to server... (${reconnectAttempts}/${maxReconnectAttempts})` : 'Connecting to plugin server…' }}
  </div>

  <div v-else-if="rootInstance" class="h-full w-full">
    <ComponentRenderer :instance="rootInstance" :rpc="rpcRef as any" />
  </div>

  <div v-else class="flex h-full w-full items-center justify-center text-sm text-gray-500">
    Waiting for plugin content...
  </div>
</template>
