// packages/app/src/App.svelte
<script lang="ts">
  import { ModeWatcher } from "mode-watcher";
  import "./app.css";
  import { createElement } from "react";
  import WorkerPluginHost from "./plugin/WorkerPluginHost.svelte";
  import PluginHost from "./plugin/PluginHost.svelte";
  import SimpleDemo from "./plugins/simple-demo";
  import AdvancedDemo from "./plugins/advanced-demo";

  type DemoType = 'simple' | 'advanced';
  type RuntimeMode = 'worker' | 'main-thread';

  let currentDemo: DemoType = $state('simple');
  let runtimeMode: RuntimeMode = $state('worker');

  // For worker mode: use plugin URLs
  let pluginUrl = $derived(
    currentDemo === 'simple' 
      ? '/src/plugins/simple-demo.tsx'
      : '/src/plugins/advanced-demo.tsx'
  );

  // For main thread mode: create React element
  let pluginElement = $derived(
    createElement(currentDemo === 'simple' ? SimpleDemo : AdvancedDemo)
  );
</script>

<ModeWatcher />
<div class="min-h-screen bg-background">
  <div class="container mx-auto px-4 py-8">
    <div class="max-w-4xl mx-auto">
      <div class="space-y-2 mb-8">
        <h1 class="text-3xl font-bold tracking-tight">
          Svelte-React Render Demo
        </h1>
        <p class="text-lg text-muted-foreground">
          React plugin rendered with beautiful shadcn-svelte components
        </p>
      </div>

      <div class="rounded-lg border bg-card text-card-foreground shadow-sm">
        <div class="p-6">
          <div class="space-y-6">
            <!-- Runtime Mode Toggle -->
            <div class="flex gap-2 items-center justify-between mb-4">
              <div class="text-sm font-medium text-muted-foreground">Runtime Mode:</div>
              <div class="flex gap-1 p-1 bg-muted rounded-lg">
                <button
                  class="inline-flex items-center justify-center gap-1 whitespace-nowrap rounded-md text-xs font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-7 px-2 {runtimeMode === 'worker' ? 'bg-background text-foreground' : 'text-muted-foreground'}"
                  onclick={() => runtimeMode = 'worker'}
                >
                  ⚡ Web Worker
                </button>
                <button
                  class="inline-flex items-center justify-center gap-1 whitespace-nowrap rounded-md text-xs font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-7 px-2 {runtimeMode === 'main-thread' ? 'bg-background text-foreground' : 'text-muted-foreground'}"
                  onclick={() => runtimeMode = 'main-thread'}
                >
                  🧵 Main Thread
                </button>
              </div>
            </div>

            <!-- Demo Tabs -->
            <div class="flex gap-1 p-1 bg-muted rounded-lg">
              <button
                class="flex-1 inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-8 px-3 {currentDemo === 'simple' ? 'bg-background text-foreground' : 'text-muted-foreground'}"
                onclick={() => currentDemo = 'simple'}
              >
                Simple Demo
              </button>
              <button
                class="flex-1 inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-8 px-3 {currentDemo === 'advanced' ? 'bg-background text-foreground' : 'text-muted-foreground'}"
                onclick={() => currentDemo = 'advanced'}
              >
                Advanced Demo
              </button>
            </div>

            <!-- Window Chrome -->
            <div class="flex items-center gap-2 pb-4 border-b">
              <div class="h-3 w-3 rounded-full bg-red-500"></div>
              <div class="h-3 w-3 rounded-full bg-yellow-500"></div>
              <div class="h-3 w-3 rounded-full bg-green-500"></div>
              <span class="ml-4 text-sm text-muted-foreground font-mono">
                {currentDemo === 'simple' ? 'simple-demo.tsx' : 'advanced-demo.tsx'}
              </span>
            </div>

            {#if runtimeMode === 'worker'}
              {#key pluginUrl}
                <WorkerPluginHost {pluginUrl} />
              {/key}
            {:else}
              <PluginHost plugin={pluginElement} />
            {/if}
          </div>
        </div>
      </div>

      <div class="mt-8 text-center text-sm text-muted-foreground space-y-1">
        <p>Built with Svelte 5, React, and shadcn-svelte</p>
        <p class="text-xs">
          {currentDemo === 'simple'
            ? 'Showing: Basic Button and Input components'
            : 'Showing: Form, Switch, and Toggle components'
          }
        </p>
        {#if runtimeMode === 'worker'}
          <p class="text-xs text-blue-500 dark:text-blue-400">
            ⚡ React plugin running in Web Worker (sandboxed)
          </p>
        {:else}
          <p class="text-xs text-green-500 dark:text-green-400">
            🧵 React plugin running in Main Thread (direct)
          </p>
        {/if}
      </div>
    </div>
  </div>
</div>

// packages/demo-react/src/App.tsx
import { useState, createElement } from 'react';
import { WorkerPluginHost } from '@/lib/plugin/WorkerPluginHost';
import { WebSocketPluginHost } from '@/lib/plugin/WebSocketPluginHost';
import { PluginHost } from '@/lib/plugin/PluginHost';
import { SimpleDemo, AdvancedDemo } from '@svelte-react-render/plugin-example';

type DemoType = 'simple' | 'advanced';
type RuntimeMode = 'worker' | 'main-thread' | 'node-server';

function App() {
  const [currentDemo, setCurrentDemo] = useState<DemoType>('simple');
  const [runtimeMode, setRuntimeMode] = useState<RuntimeMode>('worker');

  const pluginUrl = currentDemo === 'simple'
    ? 'http://localhost:3000/simple-demo.js'
    : 'http://localhost:3000/advanced-demo.js';

  const serverUrl = currentDemo === 'simple'
    ? 'ws://localhost:3001'
    : 'ws://localhost:3002';

  const pluginElement = createElement(currentDemo === 'simple' ? SimpleDemo : AdvancedDemo);

  const getModeButtonClass = (mode: RuntimeMode) => {
    const baseClass = "inline-flex h-7 items-center justify-center gap-1 rounded-md px-2 text-xs font-medium whitespace-nowrap transition-all focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50";
    return runtimeMode === mode
      ? `${baseClass} bg-background text-foreground`
      : `${baseClass} text-muted-foreground`;
  };

  const getDemoButtonClass = (demo: DemoType) => {
    const baseClass = "inline-flex h-8 flex-1 items-center justify-center gap-2 rounded-md px-3 text-sm font-medium whitespace-nowrap transition-all focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50";
    return currentDemo === demo
      ? `${baseClass} bg-background text-foreground`
      : `${baseClass} text-muted-foreground`;
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8">
        <div className="mx-auto max-w-4xl">
          <div className="mb-8 space-y-2">
            <h1 className="text-3xl font-bold tracking-tight">React Demo - Svelte-React Render</h1>
            <p className="text-lg text-muted-foreground">
              React plugins rendered with React UI components (shadcn/ui)
            </p>
          </div>

          <div className="rounded-lg border bg-card text-card-foreground shadow-sm">
            <div className="p-6">
              <div className="space-y-6">
                <div className="flex items-center justify-between gap-2">
                  <div className="text-sm font-medium text-muted-foreground">Runtime Mode:</div>
                  <div className="flex gap-1 rounded-lg bg-muted p-1">
                    <button
                      className={getModeButtonClass('worker')}
                      onClick={() => setRuntimeMode('worker')}
                    >
                      ⚡ Web Worker
                    </button>
                    <button
                      className={getModeButtonClass('node-server')}
                      onClick={() => setRuntimeMode('node-server')}
                    >
                      🖥️ Node.js
                    </button>
                    <button
                      className={getModeButtonClass('main-thread')}
                      onClick={() => setRuntimeMode('main-thread')}
                    >
                      🧵 Main Thread
                    </button>
                  </div>
                </div>

                <div className="flex gap-1 rounded-lg bg-muted p-1">
                  <button
                    className={getDemoButtonClass('simple')}
                    onClick={() => setCurrentDemo('simple')}
                  >
                    Simple Demo
                  </button>
                  <button
                    className={getDemoButtonClass('advanced')}
                    onClick={() => setCurrentDemo('advanced')}
                  >
                    Advanced Demo
                  </button>
                </div>

                <div className="flex items-center gap-2 border-b pb-4">
                  <div className="h-3 w-3 rounded-full bg-red-500" />
                  <div className="h-3 w-3 rounded-full bg-yellow-500" />
                  <div className="h-3 w-3 rounded-full bg-green-500" />
                  <span className="ml-4 font-mono text-sm text-muted-foreground">
                    {runtimeMode === 'worker'
                      ? pluginUrl
                      : runtimeMode === 'node-server'
                        ? serverUrl
                        : `${currentDemo}-demo.tsx (local)`
                    }
                  </span>
                </div>

                {runtimeMode === 'worker' && (
                  <WorkerPluginHost key={pluginUrl} pluginUrl={pluginUrl} />
                )}
                {runtimeMode === 'node-server' && (
                  <WebSocketPluginHost key={serverUrl} serverUrl={serverUrl} />
                )}
                {runtimeMode === 'main-thread' && (
                  <PluginHost plugin={pluginElement} />
                )}
              </div>
            </div>
          </div>

          <div className="mt-8 space-y-1 text-center text-sm text-muted-foreground">
            <p>Built with React 19, shadcn/ui, and @svelte-react-render/api</p>
            <p className="text-xs">
              {currentDemo === 'simple'
                ? 'Showing: Basic Button and Input components'
                : 'Showing: Form, Switch, and Toggle components'
              }
            </p>
            {runtimeMode === 'worker' && (
              <p className="text-xs text-blue-500 dark:text-blue-400">
                ⚡ React plugin running in Web Worker (loaded from external server)
              </p>
            )}
            {runtimeMode === 'node-server' && (
              <p className="text-xs text-purple-500 dark:text-purple-400">
                🖥️ React plugin running in Node.js (WebSocket communication)
              </p>
            )}
            {runtimeMode === 'main-thread' && (
              <p className="text-xs text-green-500 dark:text-green-400">
                🧵 React plugin running in Main Thread (direct)
              </p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
