// packages/api/src/components/Button.tsx
import { createElement } from 'react';
import type { ReactElement, ReactNode } from 'react';

export interface ButtonProps {
  children?: ReactNode;
  title?: string;
  icon?: string;
  variant?: 'primary' | 'secondary' | 'outline' | 'destructive' | 'ghost' | 'link';
  shortcut?: string;
  onClick?: () => void;
  className?: string;
}

export function Button({
  children,
  title,
  icon,
  variant = 'secondary',
  shortcut,
  onClick,
  className,
}: ButtonProps): ReactElement {
  return createElement(
    'Button' as any,
    {
      title,
      icon,
      variant,
      shortcut,
      onClick,
      className,
    },
    children,
  );
}

// packages/app/src/components/ui/Button.svelte
<script lang="ts">
  import Button from '$lib/components/ui/button/button.svelte';
  
  interface ButtonProps {
    title?: string;
    icon?: string;
    variant?: 'primary' | 'secondary' | 'outline' | 'destructive' | 'ghost' | 'link';
    shortcut?: string;
    onClick?: () => void;
    class?: string;
  }

  let {
    title,
    icon,
    variant = 'secondary',
    shortcut,
    onClick,
    class: className
  }: ButtonProps = $props();

  function handleClick() {
    console.log('Button clicked, onClick handler:', onClick);
    onClick?.();
    console.log('Button onClick called');
  }

  const variantMap = {
    'primary': 'default',
    'secondary': 'secondary',
    'outline': 'outline',
    'destructive': 'destructive',
    'ghost': 'ghost',
    'link': 'link'
  } as const;
</script>

<Button
  variant={variantMap[variant] || 'secondary'}
  onclick={handleClick}
  class={className}
>
  {#if icon}
    <span class="text-base">{icon}</span>
  {/if}
  {#if title}
    <span class="flex-1">{title}</span>
  {/if}
  {#if shortcut}
    <span class="text-xs opacity-60 bg-secondary px-1.5 py-0.5 rounded ml-2">{shortcut}</span>
  {/if}
</Button>
