// packages/api/src/components/Switch.tsx
import { createElement } from "react";
import type { ReactElement, ReactNode } from "react";

export interface SwitchProps {
  checked?: boolean;
  defaultChecked?: boolean;
  disabled?: boolean;
  id?: string;
  onChange?: (checked: boolean) => void;
  children?: ReactNode;
  className?: string;
}

export function Switch({
  checked,
  defaultChecked,
  disabled,
  id,
  onChange,
  children,
  className,
}: SwitchProps): ReactElement {
  return createElement(
    "Switch",
    {
      checked,
      defaultChecked,
      disabled,
      id,
      onChange,
      className,
    },
    children,
  );
}

// packages/app/src/components/ui/Switch.svelte
<script lang="ts">
  import Switch from '$lib/components/ui/switch/switch.svelte';

  interface SwitchProps {
    checked?: boolean;
    defaultChecked?: boolean;
    disabled?: boolean;
    id?: string;
    onChange?: (checked: boolean) => void;
    className?: string;
  }

  let {
    checked = false,
    defaultChecked,
    disabled,
    id,
    onChange,
    className
  }: SwitchProps = $props();

  let internalChecked = $state(checked ?? defaultChecked ?? false);

  // Update internal state when prop changes
  $effect(() => {
    if (checked !== undefined) {
      internalChecked = checked;
    }
  });

  function handleChange() {
    onChange?.(internalChecked);
  }
</script>

<Switch
  bind:checked={internalChecked}
  {disabled}
  {id}
  class={className}
  onchange={handleChange}
/>
